import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Arctic Monkeys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
      <Header/>
          {children}
      <Footer/>
      </body>
    </html>
  );
}
